server:
  port: 0
spring:
  application:
    name: event-log-sink
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    stream:
      function:
        bindings:
          loggingConsumer-in-0: input
      bindings:
        input:
          group: ${spring.application.name}
#      rabbit:
#        bindings:
#          input:
#            consumer:
#              declareExchange: false
#              bindQueue: false
      binder:
        connection-name-prefix: ${spring.application.name}
    function:
      definition: loggingConsumer
#      default:
#        contentType: "application/json"
#      bindings:
#        input:
#          destination: account.csv
#          group: ${spring.application.name}
#          consumer:
#            concurrency: 1
#        output:
#          destination: account.json
#      rabbit:
#        default:
#          group: ${spring.application.name}
#          requiredGroups: true
#          dlqQuorum:
#            enabled:  true
#          quorum:
#            enabled: true
#        bindings:
#          input:
#            consumer:
#              autoBindDlq: true
#              quorum.enabled: true
#              dlqQuorum:
#                enabled: true
#              prefetch: 10000